### ISSUE TITLE
DayZ

### ISSUE THREAD

**Issue by RecoilUK** [AlwarrenSidh/ArmAToolbox#19]
Hi

Can we use this to save models for DayZ?

Thanks

**Comment by RecoilUK** [comment]
I have been trying to use it.

I setup my model in Blender, it has a number of objects in it ...

1 - Main model.
Geometry - Copy of main model.
Land Contact - Single vertice.
Memory - Simple box surrounding model.

It exports fine, by this I mean, no errors.

But when I try to open it with the Object Builder supplied with Dayz Tools, it says, Unable to load file: Load error.

Now, I am really new to this, not new to blender, just trying this stuff and may be doing something wrong.

However, if I export as an fbx, then import that into object builder, it works.

I can even, save that file as a p3d and open it in blender.

**Comment by AlwarrenSidh** [comment]
Sadly, I have no idea what DayZ uses and if it is possible to use the Toolbox for DayZ models. It wasn't intended for it.
I'll try to see if there is any information on the topic to be had, but I can't make any promise.

**Comment by Ireheart** [comment]
Does not work with DayZ for importing.

**Comment by AlwarrenSidh** [comment]
That is what he OP said, yes. Not likely to change.
