### ISSUE TITLE
wrong mdl version

### ISSUE THREAD

**Issue by Mat-del** [AlwarrenSidh/ArmAToolbox#22]
Every time I open a model of Arma 3 it gives this error, I don't know what to do about it.
![unknown (1)](https://user-images.githubusercontent.com/70111749/90987358-c997a080-e560-11ea-8da8-c54ee5610006.png)

**Comment by AlwarrenSidh** [comment]
You are trying to open a binarized model. Binarized models cannot be opened in either ObjectBuilder nor in the ArmaToolbox in Blender, contact the author of the model and ask them for an unbinarized version.
