### ISSUE TITLE
Missing add range in the RTM Keyframes box

### ISSUE THREAD

**Issue by pmckeon** [AlwarrenSidh/ArmAToolbox#24]
I can see in a lot of tutorials that were using an earlier version of Blender and this plugin there was an option to add a range of keyframes. This option seems to be missing in the current version of this plugin, you can only individually add them one by one.

**Comment by AlwarrenSidh** [comment]
Already fixed. Do you have the latest version? I was under the impression that it already had the fix applied.

**Comment by pmckeon** [comment]
I'm running the latest released version 3.0.4
![options](https://user-images.githubusercontent.com/2910275/95015409-6ab56300-0698-11eb-8a1d-2aa8fa5448ab.jpg)
