### ISSUE TITLE
Error Cylinder p3d

### ISSUE THREAD

**Issue by Terrabe** [AlwarrenSidh/ArmAToolbox#32]
Hello AlwarrenSidh

I have a new error. This time I used blender 2.83.9 and Armatoolbox 3.0.4. I only add a cylinder and will save it as p3d. Enclosed the error message after saving. Could you please explain me, what ist wrong?
![p3d error](https://user-images.githubusercontent.com/27476178/109420387-6c2e5180-79d2-11eb-8824-76af58c0efd5.jpg)

**Comment by tfrieden** [comment]
Check the error message and you will know what is wrong. It clearly says "Model Cylinder conains n-gons and can't be exported". P3d does not support anything but triangles and quads, so to export something right away, you need to trinangulate it, or put a triangulate modifyer on it

**Comment by AlwarrenSidh** [comment]
You probably use ngons as caps. As tfrieden said, easiest fix is to add a triangulate modifier, or use "triangle fan" when creating a cylinder

**Comment by Terrabe** [comment]
Hello AllwarenSidt,

thank you for your answer. This is an solution to change every cylinder to triangle faces. But I check ist with blender 2.78c an Armatoolbox 2.7 update. Do you have in this version an automatic function to change it?

**Comment by AlwarrenSidh** [comment]
Blender 2.7 used to have a function for that, which does no longer work in 2.8x and beyond. Really the easiest way is to add a Triangulate modifier , you don't even need to apply it.

**Comment by Terrabe** [comment]
Hello AlwarrenSidh,

thank you for your help. It works. But now I must rework all models where are objects with a cylinder. Are there some other issuse, where I must make somethink different to the old versions?

**Comment by AlwarrenSidh** [comment]
As I said before, simply put a Triangulate modifier on the object and it will work.
