### ISSUE TITLE
LoW Van Model not complete when importing

### ISSUE THREAD

**Issue by 100roj** [AlwarrenSidh/ArmAToolbox#37]
LoW model only has LOD0 and LOD1 models when imported. No pilotview or cargoview models

**Comment by AlwarrenSidh** [comment]
What is a LoW model?

**Comment by 100roj** [comment]
Sorry, missed a part. I meant the Laws of War DLC Van.

**Comment by tfrieden** [comment]
You can not import binarized models

**Comment by AlwarrenSidh** [comment]
If you unbinarized the model there is no way of knowing what came out of this. The process is simply not supported, You can try to go Window -> Toggle System Console and see if there is an error message.

What I find weird is that the name of the model appears as a collection/LOD name. That should not happen.

As I said, check System Console for errors.

**Comment by 100roj** [comment]
Sorry took so long to respond, was busy with IRL problems. The console types out this when importing the Van model:
 * warning: overwrite  <class 'bpy_types.Object'> mmd_camera
 * warning: overwrite  <class 'bpy_types.Object'> mmd_rigid
 * warning: overwrite  <class 'bpy_types.Object'> mmd_joint
 * warning: overwrite  <class 'bpy_types.Object'> select
 * warning: overwrite  <class 'bpy_types.Object'> hide
 * warning: overwrite  <class 'bpy.types.Material'> mmd_material
 * warning: overwrite  <class 'bpy_types.PoseBone'> mmd_bone
 * warning: overwrite  <class 'bpy_types.PoseBone'> is_mmd_shadow_bone
 * warning: overwrite  <class 'bpy_types.PoseBone'> mmd_shadow_bone_type
 * warning: overwrite  <class 'bpy_types.PoseBone'> mmd_ik_toggle
### Loaded CATS successfully!

ValueError: the return value must be None
File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cats-blender-plugin-0-19-0\tools\settings.py", line 249, in update_settings
Signature = b'MLOD', version=257, numLods = 26
read lod
normals...
faces...
taggs
materials...
sharp edges
Normal calculation
Add edge split
set LOD type
weight
done reading lod
read lod
normals...
faces...
taggs
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ArmaToolbox\__init__.py", line 302, in execute
    error = importMDL(context, self.filepath, self.layeredLods)
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLImporter.py", line 577, in importMDL
    if loadLOD(context, filePtr, objName, materialData, layerFlag, i) != 0:
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ArmaToolbox\..\ArmaToolbox\MDLImporter.py", line 364, in loadLOD
    elif tagName[0] == '#':
<traceback object at 0x0000018FE53A4EC0>

**Comment by 100roj** [comment]
Also attaching the file I tried to open

https://drive.google.com/file/d/1gbx8kieWnWyG8-DxQQrlJdOi4z5Mi5MQ/view?usp=share_link

**Comment by AlwarrenSidh** [comment]
This looks like a faulty file structure. Unbinarizing models is generally not a good idea, it's hard to say what kind of weirdness the unbinarizer spits out.
