### ISSUE TITLE
p3d export

### ISSUE THREAD

**Issue by SaltyDevsShit** [AlwarrenSidh/ArmAToolbox#42]
no matter what i do it just throws this at me when exporting 
https://gyazo.com/7ad37c592c4a2bed1989557e349c07db

**Comment by AlwarrenSidh** [comment]
The error message essentially says it, you have n-gons in your model Cylinder.020.
Depending on what version you have, you can either

1. Add and Apply a triangulate modifier to the object if you have an older version of the toolbox
2. Newer versions have the "Apply Modifiers" checkbox in the export options. If you have that (see below) then you can just add a triangulate modifier and do not need to apply it
![image](https://user-images.githubusercontent.com/15429923/220338679-b56166be-cba7-4e90-ba36-4fa6bb64261e.png)
