### ISSUE TITLE
Attempted to start on Blender 4.0, but received an error message

### ISSUE THREAD

**Issue by 101wave** [AlwarrenSidh/ArmAToolbox#43]
![111](https://github.com/AlwarrenSidh/ArmAToolbox/assets/76065559/1a71d707-ca46-494b-b4ec-6de158997406)

**Comment by AlwarrenSidh** [comment]
Looks like you have some leftover from a previous install. Try to uninstall the addon, quit blender, make sure that the addon was completely erased, then restart blender and re-install.
Also make sure you are using the latest release:
https://github.com/AlwarrenSidh/ArmAToolbox/releases/tag/v4.0.2
