### ISSUE TITLE
doesn't work for Dayz

### ISSUE THREAD

**Issue by ZohanCtrl** [AlwarrenSidh/ArmAToolbox#44]
does not work Import and export. P3D file weighs 0 kb and dont open in Object bilder. Skript D:\Program Files (x86)\Steam\steamapps\common\DayZ Tools\Bin\ObjectBuilder\O2Script.exe no help. what to do?

**Comment by AlwarrenSidh** [comment]
That isn't much to go on. Check the log (Windows -> System Console)

**Comment by ZohanCtrl** [comment]
I don't know how to do this. how to do this and what to look for?

**Comment by AlwarrenSidh** [comment]
Use the menu... Window menu, then System Console

**Comment by ZohanCtrl** [comment]
Read prefs: C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
ArmaToolbox registering
Internal classes...
properties
registering properties
operators
menus
panels
lists
BatchMDLExport register
Register done
Read blend: C:\Users\ASUS\Desktop\Leshiy.blend
Load Hook: C:\Users\ASUS\Desktop\Leshiy.blend
CONFIG: -2
Executing script with ""
<result><null></result>



that's what it says

**Comment by AlwarrenSidh** [comment]
This cannot be all, there has to be more

**Comment by ZohanCtrl** [comment]
![blend](https://github.com/AlwarrenSidh/ArmAToolbox/assets/154552668/fbf88054-e7b6-493d-a4e6-91159f90e0c9)

that's literally all

**Comment by AlwarrenSidh** [comment]
Tell me exactly what you do.

**Comment by ZohanCtrl** [comment]
I found some instructions on YouTube. I checked the box. Simple figures are exported, complex ones are not. square or circle easily. but it's hard to figure out. There are no detailed instructions. also in English. I don't understand English well. maybe there are some instructions? which I could translate and understand. I'm new to this. It's impossible to figure it out intuitively.

**Comment by AlwarrenSidh** [comment]
If you are trying to e.g. export a cylinder, you MUST make sure there are no N-gons. Best put a triangulate modifier on every object.

**Comment by MW0XDD** [comment]
I am experiencing the same issue, even when exporting a simple cube the console output is as follows.
![image](https://github.com/AlwarrenSidh/ArmAToolbox/assets/42183456/7db3f86e-e859-4143-ab4a-921d877ed3ee)

**Comment by AlwarrenSidh** [comment]
Sorry can't help with this. Never did anything with DayZ, their O2Script might be different. The toolbox works fine with Arma...
