### ISSUE TITLE
Not working in Blender 3.1,  3.6 or 4.0

### ISSUE THREAD

**Issue by ZSMDR** [AlwarrenSidh/ArmAToolbox#47]
Installed to scripts/addons directory of each Blender version, 
then activated in the Edit / preferences menu. O2Script.exe path inserted.

Tried importing heli_light_01_civil_f.p3d from p-drive.

Got the following popup in Blender: Report Undefined Type I/O Error Wrong MDL version

![Blender 3 6 7 ArmaToolBoxImport](https://github.com/AlwarrenSidh/ArmAToolbox/assets/156422138/8edc50ee-a020-4d52-aa29-bad330f1854d)
![Blender 3 6 7 ArmaToolBox IO Error](https://github.com/AlwarrenSidh/ArmAToolbox/assets/156422138/39aeaf60-59ad-4974-9710-e571b4a7af67)

**Comment by ZSMDR** [comment]
Edit tried several p3d files. Same Error

**Comment by AlwarrenSidh** [comment]
Because models unpacked from PBO files are binarized and cannot be edited. You'll get a similar error in O2. (I think O2 will pop up an error and just show you the bounding box).

**Comment by ZSMDR** [comment]
Ok. Thank you.
