### ISSUE TITLE
P3D Export > No data being exported

### ISSUE THREAD

**Issue by H4korg** [AlwarrenSidh/ArmAToolbox#48]
When using P3D export it does not load my asset in to Object Builder. It shows a load error. Checking the P3D file it has no data. I am using Blender 4.0 and have the most up to date release of the toolbox. 

![image](https://github.com/AlwarrenSidh/ArmAToolbox/assets/42302558/45a69bba-92a6-4fa6-8ccb-7ee02bf1c73f)
![image](https://github.com/AlwarrenSidh/ArmAToolbox/assets/42302558/5e52e901-d29d-4ddf-a55e-b4458c1f8932)
![image](https://github.com/AlwarrenSidh/ArmAToolbox/assets/42302558/012d1740-817e-463f-bf21-bb71089a7960)

**Comment by AlwarrenSidh** [comment]
Was there an error during export? Since Blender's error reporting is a bit... flakey, try checking the system console

**Comment by H4korg** [comment]
> Was there an error during export? Since Blender's error reporting is a bit... flakey, try checking the system console

No errors showing in there just null.

![image](https://github.com/AlwarrenSidh/ArmAToolbox/assets/42302558/686e7cab-b98d-4359-9a60-e8aa8d10c5eb)

If I choose just export the selected only, it throws an internal handling error:

![image](https://github.com/AlwarrenSidh/ArmAToolbox/assets/42302558/bab1e554-2333-41d3-9c9a-e707667357a3)

**Comment by AlwarrenSidh** [comment]
I can't say what is going on. If possible, send me the file and I'll have a look.

**Comment by H4korg** [comment]
> I can't say what is going on. If possible, send me the file and I'll have a look.
https://www.dropbox.com/scl/fi/xc46fkkwimqs0js2k06is/weighted.blend?rlkey=p8xgi31ie64n48lxzmfvwm6ol&dl=0

**Comment by H4korg** [comment]
> I can't say what is going on. If possible, send me the file and I'll have a look.

https://www.dropbox.com/scl/fi/xc46fkkwimqs0js2k06is/weighted.blend?rlkey=p8xgi31ie64n48lxzmfvwm6ol&dl=0

**Comment by AlwarrenSidh** [comment]
None of your objects is marked as an Arma 3 object. You need to mark objects that are to be exported as such (see image)
![image](https://github.com/AlwarrenSidh/ArmAToolbox/assets/15429923/f1b8352a-3765-49bd-9a60-24f3a5e95fa4)

**Comment by AlwarrenSidh** [comment]
Yeah, but in this case it was simply because none of the objects was marked for export. 
In General, I recommend putting a triangulate modifier on everything, I am actually considering to offer an option to do that automatically.

**Comment by barman75** [comment]
> In General, I recommend putting a triangulate modifier on everything, I am actually considering to offer an option to do that automatically.

Unfortunately, sometimes it is not a good in a and texturing and testing stage, due the shading issues. Quads shades better. So, if you consider to make this feature, please make it optional. Thanks! And I really appreciate your work! This instrument is a true painkiller!

**Comment by barman75** [comment]
Oh, I forgot to menton, that auto triangulation is also sometimes works not as expected, especially on overlapped polygons. Without control, triangulation can create artifacts on non-flat overlapped surfaces. For example.
![зображення](https://github.com/AlwarrenSidh/ArmAToolbox/assets/44482847/42bba2a4-64eb-458b-ba4b-742847b68807) and for a reference
![зображення](https://github.com/AlwarrenSidh/ArmAToolbox/assets/44482847/372b24d4-6809-470e-bd1e-69c3999dfe74)

**Comment by AlwarrenSidh** [comment]
> to offer an option to do that

As I said, "offer an option"

As for the second part, overlapping UV islands in Substance Painter may generally be an issue when baking. It is recommended to move all of the overlapping parts outside of the 0..1 range, i.e. grab the parts and move them up by 1.0 along the x or y axis.  Things outside of that range are not baked by Substance.
