### ISSUE TITLE
The p3d file export was attempted using a script that utilized Blender's record operation, but an error was encountered. Could you kindly assist me with this matter?

### ISSUE THREAD

**Issue by 101wave** [AlwarrenSidh/ArmAToolbox#51]

**Comment by 101wave** [comment]
![111](https://github.com/AlwarrenSidh/ArmAToolbox/assets/76065559/2fdb149a-ad05-40f6-9f3c-b86c01b10c0f)

**Comment by 101wave** [comment]
This is the script I used
bpy.ops.object.editmode_toggle()
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
bpy.ops.object.editmode_toggle()
bpy.ops.mesh.select_all(action='DESELECT')
bpy.ops.mesh.select_mode(type='FACE', action='ENABLE')
bpy.ops.mesh.reveal()
bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.mesh.sort_elements(type='MATERIAL', elements={'FACE'}, reverse=False)
bpy.ops.mesh.select_all(action='DESELECT')
bpy.ops.object.vertex_group_set_active(group='-TOOLBOX_OPTIMIZE_TEMP')
bpy.ops.object.vertex_group_select()
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=False)
bpy.ops.object.editmode_toggle()
bpy.ops.object.delete()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
bpy.ops.object.editmode_toggle()
bpy.ops.mesh.select_all(action='DESELECT')
bpy.ops.mesh.reveal()
bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.mesh.sort_elements(type='MATERIAL', elements={'FACE'}, reverse=False)
bpy.ops.mesh.select_all(action='DESELECT')
bpy.ops.object.vertex_group_set_active(group='-TOOLBOX_OPTIMIZE_TEMP')
bpy.ops.object.vertex_group_select()
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=False)
bpy.ops.object.editmode_toggle()
bpy.ops.object.delete()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
bpy.ops.object.editmode_toggle()
bpy.ops.mesh.select_all(action='DESELECT')
bpy.ops.mesh.reveal()
bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.mesh.sort_elements(type='MATERIAL', elements={'FACE'}, reverse=False)
bpy.ops.mesh.select_all(action='DESELECT')
bpy.ops.object.vertex_group_set_active(group='-TOOLBOX_OPTIMIZE_TEMP')
bpy.ops.object.vertex_group_select()
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=False)
bpy.ops.object.editmode_toggle()
bpy.ops.object.delete()
bpy.ops.object.editmode_toggle()
bpy.ops.object.editmode_toggle()
bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
bpy.ops.object.editmode_toggle()
bpy.ops.mesh.select_all(action='DESELECT')
bpy.ops.mesh.reveal()
bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.mesh.sort_elements(type='MATERIAL', elements={'FACE'}, reverse=False)
bpy.ops.mesh.select_all(action='DESELECT')
bpy.ops.object.vertex_group_set_active(group='-TOOLBOX_OPTIMIZE_TEMP')
bpy.ops.object.vertex_group_select()
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=True)
bpy.ops.mesh.sort_elements(type='SELECTED', elements={'FACE'}, reverse=False)
bpy.ops.object.editmode_toggle()
bpy.ops.object.delete()

**Comment by AlwarrenSidh** [comment]
Huh? I don't understand, this doesn't have anything to do with the toolbox.

**Comment by 101wave** [comment]
I would like to ask for some advice, thank you for your time to reply me.

**Comment by AlwarrenSidh** [comment]
Sorry, can't help you with that, never used the Record function.
