### ISSUE TITLE
It says "I/O error: Wrong MDL version" when i try to import model

### ISSUE THREAD

**Issue by Fisheks** [AlwarrenSidh/ArmAToolbox#52]
I selected O2 script path from preferences but it didnt work for me can someone help me ?

**Comment by Fisheks** [comment]
How i can understand difference between binarized and unbinarized model ?

**Comment by AlwarrenSidh** [comment]
Open the file in a text editor. If the first four characters are MLOD then it's unbinaraized. If the first four letters are ODOL, then it is binarized, and you should consider where you got it from.
