### ISSUE TITLE
ArmAToolbox v4.0.5 not showing up in Blender v4.1

### ISSUE THREAD

**Issue by Heath3nDre4mZ** [AlwarrenSidh/ArmAToolbox#55]
Edit/Preferences/Addons/Install/ArmAToolbox--> Not showing up in addons list after clicking install. Unable to "enable" toolbox because of this. It's 99% possible that it's user error, but I followed the same steps I took for other addons. Also, the only downloads available are the Source downloads, so not sure if there is supposed to be just a "ArmAToolbox.zip" \m/

**Comment by Ice-2024** [comment]
Fixed it! Go to "C:\Users\YourUsername\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ArmAToolbox-4.0.5" There is a folder in there called "ArmaToolbox" cut that and paste it in the addons folder. So you should have

"C:\Users\YourUsername\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\ArmaToolbox", delete the ArmAToolbox-4.0.5 folder.

You should be able to enable it in blender now
