### ISSUE TITLE
Wrong MDL Version

### ISSUE THREAD

**Issue by DANIHEX** [AlwarrenSidh/ArmAToolbox#63]
Hello, I hope you are having a great time. Why am I getting an error like this: Wrong MDL Version when I try to import a p3d model into Blender 4.2.3 LTS?
![Screenshot 2024-11-18 061322](https://github.com/user-attachments/assets/69948f1f-2fc3-478f-a5ad-9ee9dc434ec6)

**Comment by AlwarrenSidh** [comment]
Because the model is binarized. You cannot import binarized models. Contact the author to get an unbinarized version of it.
